from .resnet import ResNet36_4s, ResNet43_8s
from .resnet_with_regression import ResNet43_8s_classification, ResNet43_8s_regression, ResNet43_8s_classification_regression, ResNet43_8s_classification_regression_batch

from .SEA_Net_Dual_dataset import SEA_Net_Dual_Dataset
from .SEA_Net_Seq_Dataset import SEA_Net_Seq_Dataset

from .multi_output_attention import Multi_output_attention
from .multi_output_self_attention import Multi_output_Self_Attention